### PR TITLE
Fixed all nits from PR 95-99

### LINKED ISSUE #86: Create a AddClaimCommandParser
To parse info for AddClaims command. Ensure that the claim id that the user wants to enter exists in the first place.

### PR DESCRIPTION
**Pull request by RezwanAhmed123**
Fixed based on all the review from previous PR comments, can
just merge this PR instead of having to merge all the other PRs
manually.

Fixed #86 #89 #90 #91 

Changed according to feedback from PR #95 #96 #98 #99

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/ParserUtil.java [hunk 1]
```diff
@@ -129,6 +131,43 @@ public static int parseInsurancePlan(String insurancePlanId) throws ParseExcepti
...
+     *
+     * @throws ParseException if the claim amount is not a valid positive integer
+     */
+    public static int parseClaimAmount(String claimAmount) throws ParseException {
+        requireNonNull(claimAmount);
+        int claimAmountInt;
+        try {
+            int centsInADollar = 100;
+            int claimAmountDollars = Integer.parseInt(claimAmount.trim().split("\\.")[0]);
+            if (claimAmount.trim().split("\\.")[1].length() > 2) {
```
Comment (yanqiyqh) [inline src/main/java/seedu/address/logic/parser/ParserUtil.java:159]: Can we just use claimAmountCents as calculated below already? I think its abit confusing to the reader what `claimAmount.trim().split("\\.")[1].length()` means. In the future, we could abstract it out as a method to avoid magic literals like 2, but this is just a nitpick. E.g. `if (Claim.isNotValidCents(claimAmountCents)) {}` but I'm not sure which is the best class to handle it.

**Review by yanqiyqh — CHANGES_REQUESTED** [review]
Overall LGTM, just one small nitpick to change!

File: src/main/java/seedu/address/logic/parser/ParserUtil.java (hunk 1 above)
Comment (RezwanAhmed123) [reply src/main/java/seedu/address/logic/parser/ParserUtil.java:159]: Yep, sure that improves readability, will fix!

**Review by zi-yii — APPROVED** [review]
LGTM, introducing InsurancePlanException was a good move 😄
